#!/usr/bin/env php
<?php
require_once 'bootstrap.php';

use JeroenED\Framework\Kernel;
use JeroenED\Webcron\Command\CleanupCommand;
use JeroenED\Webcron\Command\DaemonCommand;
use JeroenED\Webcron\Command\MailFailedRunsCommand;
use JeroenED\Webcron\Command\RunCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$kernel = new Kernel();

chdir(__DIR__);
$kernel->setProjectDir(getcwd());
$kernel->setConfigDir(getcwd() . '/config/');
$kernel->setTemplateDir(getcwd() . '/templates/');
$kernel->setCacheDir(getcwd() . '/cache/');
$kernel->parseDotEnv($kernel->getProjectDir() . '/.env');

$application->add(new RunCommand($kernel));
$application->add(new DaemonCommand($kernel));
$application->add(new CleanupCommand($kernel));
$application->add(new MailFailedRunsCommand($kernel));

$application->run();

