default:
  path: '/'
  controller: App\Controller\UserController::loginAction

login_check:
  path: '/login_check'

logout:
  path: '/logout'

health:
  path: '/health'
  controller: App\Controller\SiteController::healthAction

favicon:
  path: '/favicon.ico'
  controller: App\Controller\SiteController::faviconAction

settings:
  path: '/{_locale}/settings'
  methods: [ 'GET' ]
  controller: App\Controller\UserController::settingsAction

settings_save:
  path: '/{_locale}/settings'
  methods: [ 'POST' ]
  controller: App\Controller\UserController::settingsSaveAction

default_locale:
  path: '/{_locale}'
  controller: App\Controller\UserController::loginAction

login:
  path: '/{_locale}/login'
  controller: App\Controller\UserController::loginAction

webhook:
  path: '/hook/{id}/{token}'
  controller: App\Controller\JobController::hookAction
  requirements:
    id: \d+
    token: '[A-Za-z0-9]+'

job_index:
  path: '/{_locale}/job'
  controller: App\Controller\JobController::defaultAction

job_view:
  path: '/{_locale}/job/{id}/{all}'
  methods: [ 'GET' ]
  controller: App\Controller\JobController::jobAction
  defaults:
    all: false
  requirements:
    id: \d+
    all: (all|)

job_delete:
  path: '/{_locale}/job/{id}'
  methods: [ 'DELETE' ]
  controller: App\Controller\JobController::jobAction
  requirements:
    id: \d+

job_edit:
  path: '/{_locale}/job/{id}/edit'
  controller: App\Controller\JobController::editAction
  requirements:
    id: \d+

job_run:
  path: '/{_locale}/job/{id}/run/{timestamp}'
  controller: App\Controller\JobController::runAction
  requirements:
    id: \d+
    timestamp: \d+
  defaults:
    timestamp: 0

job_add:
  path: '/{_locale}/job/add'
  controller: App\Controller\JobController::addAction
