default:
  path: '/'
  defaults:
    _controller: JeroenED\Webcron\Controller\JobController::defaultAction

login:
   path: '/login'
   defaults:
     _controller: JeroenED\Webcron\Controller\SecurityController::loginAction

login_check:
  path: '/login_check'
  methods: ['POST']
  defaults:
    _controller: JeroenED\Webcron\Controller\SecurityController::loginCheckAction

job_index:
  path: '/job'
  defaults:
    _controller: JeroenED\Webcron\Controller\JobController::defaultAction

job_view:
  path: '/job/{id}'
  defaults:
    _controller: JeroenED\Webcron\Controller\JobController::viewAction
