default:
  path: '/'
  defaults:
    _controller: JeroenED\Webcron\Controller\JobController::defaultAction

login:
  path: '/login'
  defaults:
    _controller: JeroenED\Webcron\Controller\SecurityController::loginAction

logout:
  path: '/logout'
  defaults:
    _controller: JeroenED\Webcron\Controller\SecurityController::logoutAction

login_check:
  path: '/login_check'
  methods: ['POST']
  defaults:
    _controller: JeroenED\Webcron\Controller\SecurityController::loginCheckAction

job_index:
  path: '/job'
  defaults:
    _controller: JeroenED\Webcron\Controller\JobController::defaultAction

job_view:
  path: '/job/{id}/{all}'
  methods: [ 'GET' ]
  defaults:
    _controller: JeroenED\Webcron\Controller\JobController::jobAction
    all: false
  requirements:
    id: \d+

job_delete:
  path: '/job/{id}'
  methods: [ 'DELETE' ]
  defaults:
    _controller: JeroenED\Webcron\Controller\JobController::jobAction
  requirements:
    id: \d+

job_edit:
  path: '/job/{id}/edit'
  defaults:
    _controller: JeroenED\Webcron\Controller\JobController::editAction
  requirements:
    id: \d+

job_add:
  path: '/job/add'
  defaults:
    _controller: JeroenED\Webcron\Controller\JobController::addAction
