default:
  path: '/'
  defaults:
    _controller: App\Controller\JobController::defaultAction

health:
  path: '/health'
  defaults:
    _controller: App\Controller\SiteController::healthAction

login:
  path: '/login'
  defaults:
    _controller: App\Controller\SecurityController::loginAction

login_check:
  path: '/login_check'

logout:
  path: '/logout'

job_index:
  path: '/job'
  defaults:
    _controller: App\Controller\JobController::defaultAction

job_view:
  path: '/job/{id}/{all}'
  methods: [ 'GET' ]
  defaults:
    _controller: App\Controller\JobController::jobAction
    all: false
  requirements:
    id: \d+
    all: (all|)

job_delete:
  path: '/job/{id}'
  methods: [ 'DELETE' ]
  defaults:
    _controller: App\Controller\JobController::jobAction
  requirements:
    id: \d+

job_edit:
  path: '/job/{id}/edit'
  defaults:
    _controller: App\Controller\JobController::editAction
  requirements:
    id: \d+

job_runnow:
  path: '/job/{id}/runnow'
  defaults:
    _controller: App\Controller\JobController::runNowAction
  requirements:
    id: \d+

job_add:
  path: '/job/add'
  defaults:
    _controller: App\Controller\JobController::addAction
