default:
  path: '/'
  controller: App\Controller\SecurityController::loginAction

login_check:
  path: '/login_check'

logout:
  path: '/logout'

health:
  path: '/health'
  controller: App\Controller\SiteController::healthAction

favicon:
  path: '/favicon.ico'
  controller: App\Controller\SiteController::faviconAction

default_locale:
  path: '/{_locale}'
  controller: App\Controller\SecurityController::loginAction

login:
  path: '/{_locale}/login'
  controller: App\Controller\SecurityController::loginAction

job_index:
  path: '/{_locale}/job'
  controller: App\Controller\JobController::defaultAction

job_view:
  path: '/{_locale}/job/{id}/{all}'
  methods: [ 'GET' ]
  controller: App\Controller\JobController::jobAction
  defaults:
    all: false
  requirements:
    id: \d+
    all: (all|)

job_delete:
  path: '/{_locale}/job/{id}'
  methods: [ 'DELETE' ]
  controller: App\Controller\JobController::jobAction
  requirements:
    id: \d+

job_edit:
  path: '/{_locale}/job/{id}/edit'
  controller: App\Controller\JobController::editAction
  requirements:
    id: \d+

job_runnow:
  path: '/{_locale}/job/{id}/runnow'
  controller: App\Controller\JobController::runNowAction
  requirements:
    id: \d+

job_add:
  path: '/{_locale}/job/add'
  controller: App\Controller\JobController::addAction
