default:
  path: '/'
  defaults:
    _controller: JeroenED\Webcron\Controller\DefaultController::defaultAction

login:
   path: '/login'
   defaults:
     _controller: JeroenED\Webcron\Controller\SecurityController::loginAction